services:


  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_DATABASE: ems
      MYSQL_ROOT_PASSWORD: root 
    ports:
      - 3309:3306
    volumes:
      - ./mysql-data:/var/lib/mysql  
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost",'-u', 'root', '-p$MYSQL_ROOT_PASSWORD' ]
      timeout: 15s
      retries: 10
    networks:
      springboot-mysql-net:

  ems-restful-webservices:
    container_name: ems-restful-webservices
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8082:8080
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:  
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/ems
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.jpa.hibernate.ddl-auto=create
      - spring.jpa.show-sql=true
      - server.error.include-message=always
      
    networks:
      springboot-mysql-net:
    restart: on-failure:10

networks:
  springboot-mysql-net: